### ISSUE TITLE
leapp-tool runs with invalid user

### ISSUE THREAD

**Issue by JacobCZ** [leapp-to/prototype#122] opened 2017-05-16 15:11 UTC
When running the leapp-tool command directly or through cockpit, any ssh connections are established with the name of the user who ran the command, instead of the required "vagrant" user.

This can be temporarily fixed by using the ```--user=vagrant``` flag when running the command. This workaround is not applicable to cockpit.

**Comment by ncoghlan** [comment] 2017-05-17 04:34
This isn't a bug, it's a deliberate change to start decoupling LeApp from the assumption that it will always be used with Vagrant.

The Cockpit plugin should still have the user hardcoded, though - it looks like there has been a genuine regression there and the `--user` option has been lost.

**Comment by ncoghlan** [comment] 2017-05-17 04:56
See https://github.com/leapp-to/prototype/issues/46#issuecomment-301983845 for more details on the regression and why our current CI configuration didn't catch it - thanks for picking this up, and my apologies for my somewhat terse initial review on your PR at #121

**Comment by ncoghlan** [comment] 2017-05-18 01:24
@JacobCZ's fix for this has been merged in #125 - the missing test case(s) will be followed up once #46 is resolved (i.e. getting to the point where the Cockpit plugin test cases can run in CI).

**Closed by ncoghlan** 2017-05-18 01:24 UTC
